### ISSUE TITLE
[Suggestion] Open query runner in a window instead of a tab

### ISSUE THREAD

**Issue by n12o** [AntonShuvaev/intellij-dynamodb#11]
I find tabs less usable than windows when it comes to dynamodb query editor/runner. This is mainly because I'm used to having code in tabs and other functionality in windows. This is especially felt when I'm trying to open a code file and expecting query editor to stay, or when I would prefer to dock query editor to the bottom and hide/unhide it.

I'm not sure this would be a good change in all scenarios, feel free to close the issue if you don't find it a good suggestion.

**Comment by AntonShuvaev** [comment]
Hi, 

I agree that in some cases the tool window is more convenient than the editor. I chose an editor because it allows you to work with requests like with normal file, for example saving a file to a project or creating a scratch file. I don't plan to add a tool window feature yet, as it requires a lot of work.

BTW you can use IDE's split feature to achieve a similar effect.

<img width="1728" alt="Screenshot 2022-07-11 at 19 20 41" src="https://user-images.githubusercontent.com/25157138/178316894-500ed86f-b049-49ca-8428-30825daef6a1.png">
<img width="1728" alt="Screenshot 2022-07-11 at 19 18 19" src="https://user-images.githubusercontent.com/25157138/178316930-dce49b25-e471-4ca3-a66c-13680e074839.png">

**Comment by AntonShuvaev** [comment]
Starting from plugin version 2023.3.0, you can now view request logs and results in the Services tool window.
