### ISSUE TITLE
Request: Please add table names pattern to connection

### ISSUE THREAD

**Issue by dbowes-fm** [AntonShuvaev/intellij-dynamodb#20]
I only have access to certain tables that start with `abc-` ,but when I test the connection I get an error

> not authorized to perform: dynamodb:ListTables on resource: arn:aws:dynamodb:us-east-1:xxxxxxxxxxx:table/* 

I think it may work if that said `:table/abc-*` which I had put in the tables names pattern in advanced.

**Comment by AntonShuvaev** [comment]
You can specify table name pattern in configuration settings on the `Advanced` tab.

**Comment by dbowes-fm** [comment]
>  which I had put in the tables names pattern in advanced

**Comment by AntonShuvaev** [comment]
I will fix it by ignoring errors from `DescribeTable` operation which is called for each table returned from `ListTable`, so it will be not necessary to specify a table name pattern.

But the table name pattern `abc-*` (without the `table/` prefix) should work if you have permissions for `ListTable` and `DescribeTable ` for certain tables. Because the filtering happens before `DescribeTable` is called.

**Comment by AntonShuvaev** [comment]
Fixed in 2022.3.2
