### ISSUE TITLE
Quick Search in the Table Browser

### ISSUE THREAD

**Issue by dkBrazz** [AntonShuvaev/intellij-dynamodb#52]
### Is your feature request related to a problem?

From time to time I need to search for some text in the filtered result in the Table Browser, and the only possibility is to switch to json view which is not always convenient for tables with many columns

### Describe the solution you'd like

Quick Search approach similar to how it is done in the DataGrip by Cmd+F

**Comment by AntonShuvaev** [comment]
Thank you for your feedback. You can currently initiate a search by typing when the table is focused and navigate through the occurrences using the up/down arrow keys. However, I understand it's not as convenient since only the selected occurrence is highlighted. Implementing a feature similar to DataGrip's Cmd+F would indeed be better. I will do it in future versions.
